import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Sidebar from '../components/Sidebar'
import Tweets from '../components/tweets'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home /Twitter</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <div className={styles.Home}>
      <Sidebar/>
      <Tweets/>
      </div>
    </div>
  )
}
